---
kind: pipeline
type: docker
name: lint

clone:
  depth: 100

steps:
- name: eslint
  image: marcbachmann/eslint:8.0.1
  when: {event: [push]}
  depends_on: []

- name: test
  image: livingdocs/server-base:14.4
  commands: ["npm ci", "npm run test:ci -s"]
  depends_on: []

- name: release
  image: livingdocs/semantic-release:v1.2.2
  environment:
    GH_TOKEN:
      from_secret: gh_token
    NPM_TOKEN:
      from_secret: npm_token
  depends_on: [eslint, test]
