pipeline:
  eslint:
    image: marcbachmann/eslint:4.19.0
    group: test

  test:
    group: test
    image: node
    commands: ["npm install", "npm run test:ci -s"]

  publish:
    group: build
    image: marcbachmann/semantic-release:15.1.3
    secrets: [gh_token]
